
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chung
 */
public class crearplayerMenu extends javax.swing.JFrame {

    /**
     * Creates new form crearplayerMenu
     */
    public crearplayerMenu() {
        initComponents();
    }

   static player player = new player();
   pantallaInicio pantallaInicio = new pantallaInicio();
   funciones funciones = new funciones();
   menuPrincipal menuPrincipal = new menuPrincipal();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioRegistro = new javax.swing.JTextField();
        loginUsuario = new javax.swing.JTextField();
        tituloCrearplayer = new javax.swing.JTextField();
        usuarioCrear = new javax.swing.JTextField();
        fieldcrearPassword = new javax.swing.JTextField();
        passwordCrear = new javax.swing.JTextField();
        fieldcrearUsuario = new javax.swing.JTextField();
        btncrearPerfil = new javax.swing.JButton();

        usuarioRegistro.setBackground(new java.awt.Color(0, 0, 0));
        usuarioRegistro.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        usuarioRegistro.setForeground(new java.awt.Color(255, 255, 255));
        usuarioRegistro.setText("Ingrese sus datos de Ghost");
        usuarioRegistro.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        usuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioRegistroActionPerformed(evt);
            }
        });

        loginUsuario.setText("Mi usuario de ghost");
        loginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsuarioActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloCrearplayer.setBackground(new java.awt.Color(0, 0, 0));
        tituloCrearplayer.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        tituloCrearplayer.setForeground(new java.awt.Color(255, 255, 255));
        tituloCrearplayer.setText("Crear player");
        tituloCrearplayer.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tituloCrearplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloCrearplayerActionPerformed(evt);
            }
        });

        usuarioCrear.setBackground(new java.awt.Color(0, 0, 0));
        usuarioCrear.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        usuarioCrear.setForeground(new java.awt.Color(255, 255, 255));
        usuarioCrear.setText("Ingrese un nombre de usuario sin espacios");
        usuarioCrear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        usuarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCrearActionPerformed(evt);
            }
        });

        fieldcrearPassword.setText("Mi password de ghost");
        fieldcrearPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcrearPasswordActionPerformed(evt);
            }
        });

        passwordCrear.setBackground(new java.awt.Color(0, 0, 0));
        passwordCrear.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        passwordCrear.setForeground(new java.awt.Color(255, 255, 255));
        passwordCrear.setText("Ingrese una password de 8 caracteres");
        passwordCrear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        passwordCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCrearActionPerformed(evt);
            }
        });

        fieldcrearUsuario.setText("Mi usuario de ghost");
        fieldcrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcrearUsuarioActionPerformed(evt);
            }
        });

        btncrearPerfil.setBackground(new java.awt.Color(0, 0, 0));
        btncrearPerfil.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btncrearPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btncrearPerfil.setText("Crea mi perfil!");
        btncrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fieldcrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(tituloCrearplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(usuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btncrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldcrearPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tituloCrearplayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldcrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldcrearPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncrearPerfil)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloCrearplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloCrearplayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloCrearplayerActionPerformed

    private void usuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioRegistroActionPerformed

    private void usuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCrearActionPerformed

    private void loginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsuarioActionPerformed

    private void fieldcrearPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcrearPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcrearPasswordActionPerformed

    private void passwordCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordCrearActionPerformed

    private void fieldcrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcrearUsuarioActionPerformed

    private void btncrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearPerfilActionPerformed
        // TODO add your handling code here:
        String usuarioBusqueda,passwordBusqueda; 
        boolean passwordValida=true;
        usuarioBusqueda = fieldcrearUsuario.getText();
        passwordBusqueda = fieldcrearPassword.getText();
        
        funciones.validarPosicion(player.getUsuariosInfo(),usuarioBusqueda);
        funciones.validarPassword(passwordBusqueda);
        
        if(funciones.posicionUsuario==-1 && passwordValida){
        funciones.crearPlayer(player,usuarioBusqueda,passwordBusqueda);
        
        this.dispose();
        menuPrincipal.setVisible(true);
        }
        else if(funciones.posicionUsuario>-1){
        JOptionPane.showMessageDialog(null,"Ese usuario ya esta en uso, redirigiendo al menu de inicio...");
        this.dispose();
        pantallaInicio.setVisible(true);
        }
        else if(!passwordValida){
        JOptionPane.showMessageDialog(null, "Password no cumple con el requisito de 8 caracteres, redirigiendo al menu de inicio...");
        this.dispose();
        pantallaInicio.setVisible(true);
        }   
        else{
        JOptionPane.showMessageDialog(null, "Datos invalidos");
        this.dispose();
        pantallaInicio.setVisible(true);
                
         }
        
        
        
        
        
        
    }//GEN-LAST:event_btncrearPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearplayerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearplayerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearplayerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearplayerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearplayerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrearPerfil;
    private javax.swing.JTextField fieldcrearPassword;
    private javax.swing.JTextField fieldcrearUsuario;
    private javax.swing.JTextField loginUsuario;
    private javax.swing.JTextField passwordCrear;
    private javax.swing.JTextField tituloCrearplayer;
    private javax.swing.JTextField usuarioCrear;
    private javax.swing.JTextField usuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
